name: Auto Rebuild on Base Image Update

permissions:
  contents: read
  packages: write
  actions: write

on:
  schedule:
    # Check for updates every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual trigger
  
jobs:
  check-and-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get current base image digest
        id: base-digest
        run: |
          # Pull the image to get its digest
          docker pull ghcr.io/hotio/prowlarr:latest
          DIGEST=$(docker inspect ghcr.io/hotio/prowlarr:latest --format='{{index .RepoDigests 0}}' | cut -d'@' -f2)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Current digest: $DIGEST"
          
      - name: Check if rebuild needed
        id: check-rebuild
        run: |
          # Get the last successful build's base image digest from repository variables
          LAST_DIGEST="${{ vars.LAST_BASE_DIGEST || 'none' }}"
          CURRENT_DIGEST="${{ steps.base-digest.outputs.digest }}"
          
          if [ "$LAST_DIGEST" != "$CURRENT_DIGEST" ]; then
            echo "rebuild=true" >> $GITHUB_OUTPUT
            echo "Base image updated. Rebuild needed."
          else
            echo "rebuild=false" >> $GITHUB_OUTPUT
            echo "No update needed."
          fi
          
      - name: Build and push
        if: steps.check-rebuild.outputs.rebuild == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.visibility=public
          
      - name: Update base image digest
        if: steps.check-rebuild.outputs.rebuild == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Update repository variable with new digest using gh CLI
          # https://github.com/almottier/prowlarr-ygg/settings/variables/actions
          gh variable set LAST_BASE_DIGEST --body "${{ steps.base-digest.outputs.digest }}"